### ISSUE TITLE
[C#] enum이란?

### ISSUE THREAD

**Issue by ggjae** [TIOGx/Unity#14]
# enum

열거형이라고 불리는데 어떤것을 분류하고 싶을 때 자주 사용하게 된다.  
말로만 이해하는 것은 어렵기 때문에 예제를 참조하여 공부해보자.

간단한 RPG 게임에서의 인벤토리안에 있을 아이템들을 생각해보자.
장비아이템, 포션아이템, 퀘스트아이템, 기타아이템, 캐시아이템을 전부 클래스로 만들어서 관리해주어야 할까?
class 장비, class 포션, class 퀘스트, class 기타, class 캐시

그렇다면 **장비에도 머리, 견갑, 상의, 하의, 장갑** 등이 있고, **포션에도 HP포션, MP포션** 등 이런것들도 전부 세부클래스로 나누어 줄 것인가?라는 고민을 분명 할 수 있다.

> 이런식으로 만드는 것은 가독성이 떨어질 뿐만 아니라 우리에게 불편함을 주게 된다.

그렇기 때문에, 다양한 ItemType들을 enum 열거형을 사용하여 정리하여주고, class Item에서 itemtype을 채용해주면 좋다.
   
ex)
```cs
enum ITEMTYPE {
    EQUIP,
    POTION,
    QUEST,
    ETC,
    CASH
}

class Item {
    int ItemType;
    int level;

}
```
ItemType이 0이면 equip이고, 1이면 potion이고.... 하지만 사람들이 읽을 때 itemtype 0이 뭐지? 1이 뭐지? 가독성이 떨어지고 한눈에 들어오지 않는다. 
하지만 열거형을 더 활용한다면 밑에 볼 코드를 작성할 수 있다.

```cs
enum ITEMTYPE {
    EQUIP,
    POTION,
    QUEST,
    ETC,
    CASH,
    NONESELECT
}

class Item {
    ITEMTYPE ItemType = ITEMTYPE.NONESELECT;
    int level = 1;

}
```

내가 만약 포션을 만들고싶다고 하면,
```cs
static void main(string[] args){
    Item NewItem = new Item();
    NewItem.ItemType = ITEMTYPE.POTION;
```

enum을 사용해서 내가 어떤 case들을 정리할 수 있구나. 정한 타입처럼 사용할 수 있는것이다.
협업에서 코드를 이해하기 쉽지 않을때가 있는데 enum을 사용한다면 협업에서 더 큰 이점을 얻을 수 있을것이다.
아직도 이해가 되지 않았다면? 실제 게임에서 적용할법한 예시를 살펴보자.

```cs
// class 참조형 사용자정의
// struct 갑형 사용자정의
// enum 값형 사용자정의
ITEMTYPE Type = newItem.ItemType;
switch(Type)
{
    case ITEMTYPE.EQUIP:
         장비메소드();
         break;
    case ITEMTYPE.POTION:
         포션메소드();
         break;
}
```

ref) 어소트락 게임아카데미학원 C# 공개강의 YOUTUBE

**Comment by ggjae** [comment]
Switch문과 궁합이 정말 좋다고 합니다!

**Comment by wogns0197** [comment]
오 Enum은 정말 정말 정말 유용합니다 
아주 좋아요
